const runtime=new URL(new URLSearchParams(location.search).has('dev')?'../../salty-ext/':'../../',import.meta.url);
const {fixture,core,engine}=await import('./diagnostics-stub.js');
const ctx={name1:'Reader',name2:'Guide',extensionSettings:{},chatMetadata:{memoria:{turns:[]}},chat:[{mes:'synthetic'},{mes:'synthetic'}],powerUserSettings:{},saveSettingsDebounced(){},getRequestHeaders:()=>({})};
window.SillyTavern={getContext:()=>ctx};
const errors=[];window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>{errors.push(String(e.reason));document.querySelector('#results').textContent=String(e.reason?.stack||e.reason)});
const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('style.css',runtime);document.head.append(css);await new Promise(r=>css.onload=r);
const {getSettings}=await import(new URL('src/settings.js',runtime));
const {applyAll}=await import(new URL('src/apply.js',runtime));
const {mountPanel,unmountPanel}=await import(new URL('src/panel.js',runtime));
const {readFavorites,toggleFavorite}=await import(new URL('src/settings-favorites.js',runtime));
const {compareRegex,skipReason}=await import(new URL('src/regex-compare-core.js',runtime));
const {prepareRules}=await import(new URL('src/settings-tools.js',runtime));
const {collectProblems,safeFailure}=await import('./diagnostics-stub.js');
localStorage.setItem('salty_tab','theme');localStorage.removeItem('salty_favorites');
getSettings().profile.original=false;getSettings().userProfile.original=false;applyAll();
let panel=mountPanel(document.querySelector('#panel'));
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const until=async fn=>{for(let i=0;i<100&&!fn();i++)await pause(40);if(!fn())throw new Error('대기 초과');};
const route=(tab,sub)=>panel.querySelector(`[data-act="editor-route"][data-tab="${tab}"][data-sub="${sub}"]`).click();
const action=a=>panel.querySelector(`[data-tool-action="${a}"]`).click();
const rule=(name,find,replace,other={})=>({scriptName:name,findRegex:find,replaceString:replace,placement:[2],markdownOnly:true,trimStrings:[],...other});
document.querySelector('#progress').textContent='준비 완료';
document.querySelector('#run').onclick=async()=>{
 const checks=[],check=(name,pass,detail)=>checks.push({name,pass:!!pass,detail});
 try{
 route('chat','screen');
 panel.querySelector('[data-act="editor-catalog"]').click();
 const pin=panel.querySelector('.bl-favorites header [data-favorite]');pin.click();
 check('current section pin persists',readFavorites().some(e=>e.sub==='screen'));
 const search=panel.querySelector('[data-settings-search]');search.value='QR 편집';search.dispatchEvent(new Event('input',{bubbles:true}));
 const qr=panel.querySelector('.bl-search-result-row');qr.querySelector('[data-favorite]').click();
 check('search result pin includes subsection anchor',readFavorites().some(e=>e.anchor==='퀵 리플라이'));
 panel.querySelector('[data-settings-clear]').click();
 const favorite=[...panel.querySelectorAll('[data-favorite-jump]')].find(e=>JSON.parse(e.dataset.favoriteJump).anchor==='퀵 리플라이');favorite.click();
 check('favorite opens exact settings group',panel.querySelector('.salty-sec').dataset.sub==='screen'&&panel.querySelector('.bl-search-target')?.textContent.includes('퀵 리플라이'));
 unmountPanel(panel);panel=mountPanel(document.querySelector('#panel'));check('favorites survive panel remount',panel.querySelectorAll('[data-favorite-jump]').length===2);
 route('prompt','regex');await until(()=>panel.querySelector('[data-rx="input"]'));
 check('diagnostics stay idle until requested',fixture.reads===0);
 fixture.rules=[rule('속마음 색','/\\[([^\\]]+)\\]/g','<span style="color:purple">$1</span>'),rule('이름','/Guide/g','Captain'),rule('다른 대상','/hello/g','x',{placement:[1]}),rule('꺼짐','/hello/g','x',{disabled:true}),rule('잘못된 식','/[broken/','x')];
 panel.querySelector('[data-rx="input"]').value='Guide [hello]';action('compare');await until(()=>panel.querySelector('.bl-tool-traces'));
 check('worker applies ordered captures and colors',panel.querySelectorAll('.bl-tool-columns pre')[1].textContent==='Captain <span style="color:purple">hello</span>');
 const preview=panel.querySelector('.bl-tool-preview');check('color preview is sandboxed without script permission',preview?.getAttribute('sandbox')===''&&preview.srcdoc.includes("default-src 'none'")&&preview.srcdoc.includes('color:purple'));
 check('rule reasons and invalid regex displayed',panel.textContent.includes('대상 다름')&&panel.textContent.includes('꺼진 규칙')&&panel.textContent.includes('올바르지'));
 check('side by side input retained',panel.querySelector('.bl-tool-columns pre').textContent==='Guide [hello]');
 check('mobile columns fit',panel.querySelector('.bl-tool-columns').scrollWidth<=panel.querySelector('.bl-tool-columns').clientWidth+1);
 check('regex does not edit chat or scripts',ctx.chat[0].mes==='synthetic'&&fixture.rules[0].replaceString.includes('$1'));
 const options={placement:2,mode:'display',depth:0,edit:false};
 check('stage, depth and edit eligibility',skipReason(rule('a','a','b',{markdownOnly:false}),options)==='적용 단계 다름'&&skipReason(rule('a','a','b',{minDepth:2}),options)==='최소 깊이 밖'&&skipReason(rule('a','a','b'),{...options,edit:true})==='편집 시 적용 꺼짐');
 fixture.rules=[rule('named','/(?<word>hello)/g','{{char}} $<word> {{match}}',{trimStrings:['ll']})];
 const named=compareRegex('hello',prepareRules(engine,ctx,options));check('named, full match, trims, safe names',named.output==='Guide heo heo');
 fixture.rules=[rule('macro','/a/','{{setvar::secret::x}}')];check('mutating macros never executed',compareRegex('a',prepareRules(engine,ctx,options)).output==='{{setvar::secret::x}}');
 fixture.rules=[rule('explosive','/x/g','y'.repeat(5000))];check('output growth bounded',compareRegex('x'.repeat(100),prepareRules(engine,ctx,options)).traces[0].error);
 fixture.rules=[rule('slow','/(a+)+$/','x')];panel.querySelector('[data-rx="input"]').value='a'.repeat(32)+'!';action('compare');await until(()=>panel.querySelector('[data-tool-status]').textContent.includes('2초'));
 check('catastrophic regex times out without freezing UI',panel.querySelector('[data-tool-status]').textContent.includes('중단'));
 action('compare');await pause(100);route('text','text');await pause(100);check('leaving tool removes running worker view',!panel.querySelector('[data-settings-tool]'));
 ctx.chatMetadata.memoria.turns=[{mesId:0,failed:true,failure:{message:'JSON 응답 잘림',at:Date.now()}}];
 fixture.entries=[{caller:'llm-translator-custom',ok:false,status:429,error:'quota',at:Date.now()},{caller:'chat',ok:false,status:401,error:'Bearer fake-secret sk-secret https://private.invalid',at:Date.now()},{caller:'chat',ok:true,status:200},{caller:'chat',ok:false,aborted:true}];
 route('theme','problems');await until(()=>panel.querySelectorAll('.bl-problem').length===3);
 check('combines memory translation and request failures',panel.querySelectorAll('.bl-problem').length===3);
 check('failure advice and credentials redacted',panel.textContent.includes('잔액')&&!panel.textContent.includes('fake-secret')&&!panel.textContent.includes('private.invalid'));
 const filter=panel.querySelector('[data-issue-filter]');filter.value='translation';filter.dispatchEvent(new Event('change',{bubbles:true}));check('filters translation errors',panel.querySelectorAll('.bl-problem').length===1);
 filter.value='all';filter.dispatchEvent(new Event('change',{bubbles:true}));fixture.key='other';panel.querySelector('[data-tool-retry]').click();await pause(80);
 check('retry blocked after chat switch',!fixture.commits.length&&panel.textContent.includes('채팅이 바뀌었'));
 fixture.key='synthetic';core.runtime.busy=1;panel.querySelector('[data-tool-retry]').click();await pause(80);check('retry blocked while busy',!fixture.commits.length);
 core.runtime.busy=0;panel.querySelector('[data-tool-retry]').click();await until(()=>fixture.commits.length===1&&panel.querySelectorAll('.bl-problem').length===2);
 check('retry targets failed memory message only',fixture.commits[0]===0&&!ctx.chatMetadata.memoria.turns[0].failed);
 action('request-log');await until(()=>document.querySelector('#log-open').textContent==='열림');check('request log navigation',true);
 const count=fixture.reads;await pause(150);check('no idle diagnostic polling',fixture.reads===count);
 fixture.missing=true;action('refresh');await until(()=>panel.textContent.includes('Perf Assist'));check('missing extensions explained',panel.textContent.includes('연결되지 않아'));
 const hiddenContainer=document.createElement('div');hiddenContainer.hidden=true;document.body.append(hiddenContainer);const hiddenReads=fixture.reads,hiddenPanel=mountPanel(hiddenContainer);await pause(150);
 check('closed drawer does not read records',fixture.reads===hiddenReads);
 hiddenContainer.hidden=false;hiddenContainer.scrollIntoView();await until(()=>fixture.reads>hiddenReads);check('opening hidden drawer loads tool',!!hiddenPanel.querySelector('[data-issue-filter]'));unmountPanel(hiddenPanel);hiddenContainer.remove();
 check('no body content copied to issue model',!JSON.stringify(collectProblems(ctx,[{ok:false,error:'oops',prompt:'private prompt',reply:'private reply'}])).includes('private'));
 check('all header tool controls fit mobile',panel.querySelector('.bl-tool-options').scrollWidth<=panel.querySelector('.bl-tool-options').clientWidth+1);
 route('theme','palette');check('existing settings still reachable',!!panel.querySelector('[data-num="lightTint"]'));
 check('no runtime errors',errors.length===0,errors);
 }catch(error){check('unexpected test error',false,String(error.stack));}
 document.querySelector('#results').textContent=JSON.stringify({total:checks.length,passed:checks.filter(c=>c.pass).length,width:innerWidth,checks},null,2);document.querySelector('#progress').textContent='완료';
};
