// Synthetic benchmark: real runtime modules and host CSS, no user data or API calls.
const output=document.querySelector('#results'),progress=document.querySelector('#progress'),button=document.querySelector('#run');
const probes=[],errors=[];
const {checkVariableUpdates}=await import('./variable-updates.js');
for(const type of ['ResizeObserver','IntersectionObserver']){const Native=window[type];window[type]=class extends Native{constructor(fn,opts){const stat={type,targets:new Set(),calls:0};super((...args)=>{stat.calls++;fn(...args)},opts);this.stat=stat;probes.push(stat)}observe(el,...args){this.stat.targets.add(el);return super.observe(el,...args)}unobserve(el){this.stat.targets.delete(el);return super.unobserve(el)}disconnect(){this.stat.targets.clear();return super.disconnect()}}}
window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
const ctx={extensionSettings:{},powerUserSettings:{},characters:[],saveSettingsDebounced(){},getRequestHeaders:()=>({}),eventSource:{on(){}},event_types:{CHAT_CHANGED:'chat'}};window.SillyTavern={getContext:()=>ctx};window.toastr={error:x=>errors.push(x),info(){},warning(){},success(){}};
const runtime=new URL(new URLSearchParams(location.search).has('dev')?'../../salty-ext/':'../../',import.meta.url);
const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('style.css',runtime);document.head.append(css);await new Promise((r,j)=>{css.onload=r;css.onerror=j});
const {getSettings}=await import(new URL('src/settings.js',runtime));const {applyAll}=await import(new URL('src/apply.js',runtime));const {startAssetWatcher}=await import(new URL('src/assets.js',runtime));const {mountPanel,refreshPanels,unmountPanel}=await import(new URL('src/panel.js',runtime));const {presetFrame}=await import(new URL('src/frame-library.js',runtime));
const frame=()=>new Promise(r=>requestAnimationFrame(r));const settle=async()=>{for(let i=0;i<5;i++)await frame()};
const image='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect width="400" height="300" fill="#94b6ca"/><circle cx="200" cy="130" r="85" fill="#fae0b4"/></svg>');
function message(i){return '<div class="mes" mesid="'+i+'" is_user="'+(i%4===1)+'" is_system="false"><div class="mesAvatarWrapper"><div class="avatar"><img src="'+image+'" alt="합성 프로필"></div><div class="mesIDDisplay">#'+i+'</div></div><div class="mes_block"><div class="ch_name"><span class="name_text">검사용 캐릭터</span><small class="timestamp">가상 시간</small><div class="mes_buttons"><span class="mes_button extraMesButtonsHint">⋯</span><span class="mes_button mes_edit">✎</span></div></div><div class="mes_text">'+Array.from({length:4},()=>'<p>성능 검사용 합성 문장입니다. <q>대사의 형광펜과 간격을 확인합니다.</q> '+('길어진 채팅에서도 원래 기능을 유지합니다. '.repeat(4))+'</p>').join('')+(i%4===0?'<img class="eh-img" src="'+image+'" alt="합성 에셋">':'')+'</div></div></div>'}
const s=getSettings();s.profile.original=s.userProfile.original=false;s.image.fade='off';s.image.blendWhite=false;s.image.layout='column';s.profile.mode='small';s.chat.colorPop=s.chat.selectPop=false;
applyAll();startAssetWatcher();progress.textContent='준비 완료';
const stats=values=>{const a=[...values].sort((a,b)=>a-b);return {median:+a[Math.floor(a.length/2)].toFixed(2),p95:+a[Math.floor(a.length*.95)].toFixed(2),max:+a.at(-1).toFixed(2)}};
button.onclick=async()=>{button.disabled=true;const checks=[],cases=[],check=(name,pass,detail)=>checks.push({name,pass:!!pass,detail});const chat=document.querySelector('#chat');
try{for(const [count,decor] of [[100,false],[1000,false],[1000,true]]){progress.textContent=count+'개 메시지 / 액자 '+decor;s.image.decor=decor?presetFrame('browser'):{...s.image.decor,on:false};s.enabled=true;applyAll();await settle();const t=performance.now();chat.innerHTML=Array.from({length:count},(_,i)=>message(i)).join('');await Promise.all([...chat.querySelectorAll('img')].map(im=>im.decode().catch(()=>{})));await settle();const initial=performance.now()-t;const parent=document.querySelector('#panel');const panel=mountPanel(parent);await settle();const refresh=[],applyTimes=[],panelTimes=[];for(let i=0;i<10;i++){const t=performance.now();s.type.size=16+(i%2);applyAll();const afterApply=performance.now();refreshPanels();applyTimes.push(afterApply-t);panelTimes.push(performance.now()-afterApply);refresh.push(performance.now()-t);await frame()}const intervals=[],scrollCost=[];let prev=performance.now();for(let i=0;i<60;i++){const t=performance.now();chat.scrollTop=(chat.scrollHeight-chat.clientHeight)*i/59;scrollCost.push(performance.now()-t);await frame();const now=performance.now();intervals.push(now-prev);prev=now}const stream=chat.querySelector('.mes:last-child .mes_text p:last-of-type');const streamMs=[];for(let i=0;i<20;i++){const t=performance.now();stream.append(document.createTextNode(' 추가'));await frame();streamMs.push(performance.now()-t)}check(count+'/'+decor+' message count',chat.querySelectorAll('.mes').length===count);check(count+'/'+decor+' asset classification',chat.querySelectorAll('.salty-asset').length===count/4);check(count+'/'+decor+' frame count',chat.querySelectorAll('[data-bl-frame="image"]').length===(decor?count/4:0));unmountPanel(panel);parent.replaceChildren();await settle();cases.push({messages:count,assetImages:count/4,decor,initialMs:+initial.toFixed(2),settingsMs:stats(refresh),applyMs:stats(applyTimes),panelMs:stats(panelTimes),scrollFrameMs:stats(intervals),scrollWriteMs:stats(scrollCost),streamFrameMs:stats(streamMs),visibility:document.visibilityState,frameTimingUsable:intervals.every(x=>x<200),domNodes:chat.querySelectorAll('*').length});chat.replaceChildren();await settle();check(count+'/'+decor+' removed images released',probes.flatMap(p=>[...p.targets]).filter(x=>!x.isConnected).length===0,{detachedObserved:probes.flatMap(p=>[...p.targets]).filter(x=>!x.isConnected).length});}
for(let i=0;i<10;i++){chat.innerHTML=Array.from({length:20},(_,n)=>message(n)).join('');await settle();chat.replaceChildren();await settle()}check('ten chat replacements release detached observation targets',probes.flatMap(p=>[...p.targets]).filter(x=>!x.isConnected).length===0);
s.enabled=false;applyAll();await settle();check('disabled removes decorative wrappers',document.querySelectorAll('#chat .bl-art-frame').length===0);const callbacks=()=>probes.reduce((n,p)=>n+p.calls,0);const before=callbacks();for(let i=0;i<20;i++)await frame();check('idle scene has no resize or visibility callbacks',callbacks()===before);checks.push(...checkVariableUpdates(s,applyAll));check('no runtime errors',errors.length===0,errors);output.textContent=JSON.stringify({total:checks.length,passed:checks.filter(x=>x.pass).length,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},cases,checks,limits:'Synthetic local fixture. Includes asset watcher, decor, profiles, settings, apply path and host CSS; not the entire SillyTavern server or third-party extensions. Frame timing depends on foreground state and machine load.'},null,2);progress.textContent='완료';}catch(e){output.textContent=e.stack;progress.textContent='검사 오류'}finally{button.disabled=false}};
