import assert from 'node:assert/strict';
import {pathToFileURL,fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(process.argv[2]||fileURLToPath(new URL('../..',import.meta.url)));
const {DEFAULTS,getSettings}=await import(pathToFileURL(path.join(root,'src/settings.js')));
const {captureStyle,applyStyleData,sharePayload,encodeStyle,decodeStyle}=await import(pathToFileURL(path.join(root,'src/styles.js')));
const {syncChat}=await import(pathToFileURL(path.join(root,'src/charstyle.js')));
const ctx={extensionSettings:{},powerUserSettings:{},characters:[{avatar:'qa-a.png'},{avatar:'qa-b.png'}],characterId:0,saveSettingsDebounced(){}};
globalThis.SillyTavern={getContext:()=>ctx};
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';
const results=[];async function test(name,fn){try{await fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message})}}
function load(value){ctx.extensionSettings.salty=structuredClone(value);return getSettings()}
function rich(){const s=structuredClone(DEFAULTS);s.profile.modeVersion=1;s.palette='melon-night';s.nightTint=13;s.lightTint=7;s.type.size=23;s.type.indent=true;s.fonts.text.ko='qa-font';s.customFonts=[{id:'qa-font',family:'QA Synthetic Font',file:'data:font/woff2;base64,dGVzdA=='}];s.profile.mode='banner';s.userProfile.mode='small';s.userProfile.side='right';s.profile.decor={...s.profile.decor,on:true,art:png,mask:png,radius:37,frameWidth:145,frameHeight:80,libraryId:'qa-frame'};s.frameLibrary=[{id:'qa-frame',name:'저장 액자',decor:structuredClone(s.profile.decor)}];s.image.masks=[{id:'qa-mask',name:'저장 도형',data:png}];s.image.maskId='qa-mask';s.image.mask=png;s.image.shape='custom';s.weatherImages=[{id:'qa-weather',name:'날씨',data:png}];s.chat.weatherImageId='qa-weather';s.chat.weatherImage=png;s.colorOverrides={'melon-night':{bg:'#202124',marker:'#baedbc'}};s.styles=[{id:'qa-style',name:'저장 스타일',data:captureStyle(s)}];s.charStyles={'c:qa-a.png':'qa-style','g:qa-group':'qa-style'};return s}
await test('current settings preserve all custom resources on upgrade',()=>{const before=rich(),after=load(before);for(const key of ['frameLibrary','customFonts','styles','charStyles','colorOverrides','fonts','image','weatherImages','profile','userProfile'])assert.deepEqual(after[key],before[key],key)});
await test('ten save/reload cycles remain identical',()=>{let s=load(rich()),before=JSON.stringify(s);for(let i=0;i<10;i++)s=load(JSON.parse(JSON.stringify(s)));assert.equal(JSON.stringify(s),before)});
await test('schema 1 preserves font choice and migrates old alignment',()=>{const s=load({version:1,fonts:{text:'qa-old',dialogue:'same',ui:'qa-ui'},type:{size:21,justify:true},chat:{user:'line'}});assert.equal(s.fonts.text.ko,'qa-old');assert.equal(s.fonts.ui.ko,'qa-ui');assert.equal(s.type.align,'justify-word');assert.equal(s.type.size,21);assert.equal(s.chat.user,'plain');assert.equal(s.version,4)});
await test('schema 2 fills new fields without replacing saved resources',()=>{const old=rich();old.version=2;delete old.lightTint;delete old.nightTint;delete old.userProfile;const s=load(old);assert.equal(s.lightTint,.5);assert.equal(s.nightTint,1);assert.deepEqual(s.frameLibrary,old.frameLibrary);assert.deepEqual(s.customFonts,old.customFonts);assert.deepEqual(s.charStyles,old.charStyles)});
await test('legacy user profile inherit follows existing avatar preference once',()=>{ctx.powerUserSettings.hideChatAvatars_enabled=true;const old=rich();old.userProfile.mode='inherit';const s=load(old);assert.equal(s.userProfile.mode,'none');s.userProfile.mode='small';assert.equal(getSettings().userProfile.mode,'small');ctx.powerUserSettings.hideChatAvatars_enabled=false});
await test('style JSON and code round trip retain tint and artwork',async()=>{const s=load(rich()),payload=sharePayload('검사',captureStyle(s),s);for(const input of [JSON.stringify(payload),await encodeStyle(payload)]){const decoded=await decodeStyle(input);assert.equal(decoded.style.nightTint,13);assert.equal(decoded.style.lightTint,7);assert.equal(decoded.style.profile.decor.art,png);assert.equal(decoded.fonts[0].id,'qa-font')}});
await test('switch linked character and restore base style including tint',()=>{const s=load(rich());s.nightTint=2;s.lightTint=1;s.type.size=17;ctx.characterId=0;assert.equal(syncChat(),true);assert.equal(s.type.size,23);assert.equal(s.nightTint,13);assert.equal(s.lightTint,7);const persisted=JSON.parse(JSON.stringify(s));load(persisted);ctx.characterId=1;assert.equal(syncChat(),true);const restored=getSettings();assert.equal(restored.type.size,17);assert.equal(restored.nightTint,2);assert.equal(restored.lightTint,1);assert.equal(restored.frameLibrary.length,1);assert.equal(restored.customFonts.length,1);assert.equal(restored.activeStyle,null)});
await test('legacy partial styles leave new tint values intact',()=>{const s=load(rich());applyStyleData(s,{type:{...s.type,size:18}});assert.equal(s.nightTint,13);assert.equal(s.lightTint,7);assert.equal(s.frameLibrary.length,1)});
await test('style application preserves behavior and shared libraries',()=>{const s=load(rich());s.chat.qrFind=false;const style=captureStyle(s);style.chat.qrFind=true;s.type.size=18;applyStyleData(s,style);assert.equal(s.chat.qrFind,false);assert.equal(s.image.mask,png);assert.equal(s.image.masks.length,1);assert.equal(s.frameLibrary.length,1);assert.equal(s.weatherImages.length,1)});
console.log(JSON.stringify({total:results.length,passed:results.filter(x=>x.pass).length,results},null,2));if(results.some(x=>!x.pass))process.exitCode=1;
