import {SCRIPT_CATALOG} from '../../scripts/catalog.js';
import {scriptSettings,persistScripts,replaceScriptSettings,legacyConflicts} from '../../scripts/store.js';
import {syncScripts,scriptStatus,subscribeScripts} from '../../scripts/runtime.js';
import {scanEnglish} from '../../scripts/scan.js';
export function installLocalizationPage({doc}){
 const tab=doc.createElement('button');tab.type='button';tab.className='pt-tab';tab.dataset.tab='localization';tab.textContent='한글화';doc.getElementById('pt-tabs').prepend(tab);
 const page=doc.createElement('div');page.id='pt-page-localization';page.className='pt-page';page.innerHTML='<p class="pt-bl-help">메뉴와 정해진 이름을 준비된 사전으로 바꿔요. API 요금 없이 바로 적용되며 기존 한글화 설정을 이어 써요. 자료 본문은 옆 탭에서 API로 번역하세요.</p><div class="pt-localization-list"></div><button type="button" class="pt-ui-button" data-locale-scan>남은 영어 찾기</button><p role="status" data-locale-status></p><textarea aria-label="남은 영어 결과" data-locale-result readonly hidden></textarea>';
 doc.getElementById('pt-panel-content').append(page);const list=page.querySelector('.pt-localization-list'),status=page.querySelector('[data-locale-status]');let busy=false;
 for(const item of SCRIPT_CATALOG.filter(item=>item.id!=='fold')){
  const row=doc.createElement('section');row.className='pt-card';const label=doc.createElement('label');label.className='pt-check';const input=doc.createElement('input');input.type='checkbox';input.dataset.localeToggle=item.id;input.checked=scriptSettings().enabled[item.id];const title=doc.createElement('span');title.textContent=item.name;label.append(input,title);const description=doc.createElement('p');description.className='pt-bl-help';description.textContent=item.description;const state=doc.createElement('small');state.dataset.localeState=item.id;row.append(label,description,state);list.append(row);
  const recovery=doc.createElement('div');recovery.className='pt-locale-override';recovery.dataset.localeOverride=item.id;
  const exportCode=doc.createElement('button');exportCode.type='button';exportCode.className='pt-ui-button';exportCode.textContent='수정 코드 내보내기';exportCode.dataset.localeExport=item.id;
  const restore=doc.createElement('button');restore.type='button';restore.className='pt-ui-button';restore.textContent='기본 코드로 복원';restore.dataset.localeRestore=item.id;recovery.append(exportCode,restore);row.append(recovery);
  exportCode.onclick=()=>{const code=scriptSettings().overrides[item.id]?.code;if(typeof code!=='string')return;const url=URL.createObjectURL(new Blob([code],{type:'text/javascript;charset=utf-8'}));const a=doc.createElement('a');a.href=url;a.download=`blue-lemonade-${item.id}-custom.js`;doc.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='수정 코드를 파일로 내보냈어요.';};
  restore.onclick=async()=>{if(busy||!scriptSettings().overrides[item.id])return;if(!doc.defaultView.confirm('이 항목을 기본 코드로 복원할까요? 수정 코드를 보관하려면 먼저 내보내 주세요.'))return;busy=true;const before=structuredClone(scriptSettings());delete scriptSettings().overrides[item.id];paint();try{await persistScripts();await syncScripts(true);status.textContent='기본 코드로 복원했어요. 켜기 설정은 그대로예요.';}catch(error){replaceScriptSettings(before);status.textContent=error.message;}finally{busy=false;paint();}};
  input.onchange=async()=>{if(busy)return;if(input.checked&&legacyConflicts(item.id).length){input.checked=false;status.textContent='헬퍼의 스크립트 관리에서 같은 스크립트를 끈 뒤 다시 켜 주세요.';return;}busy=true;const before=structuredClone(scriptSettings());scriptSettings().enabled[item.id]=input.checked;paint();try{await persistScripts();await syncScripts(true);status.textContent='저장하고 적용했어요.';}catch(error){replaceScriptSettings(before);status.textContent=error.message;}finally{busy=false;paint();}};
 }
 function paint(){for(const input of page.querySelectorAll('[data-locale-toggle]')){input.checked=scriptSettings().enabled[input.dataset.localeToggle];input.disabled=busy;}for(const label of page.querySelectorAll('[data-locale-state]'))label.textContent=scriptStatus(label.dataset.localeState);for(const actions of page.querySelectorAll('[data-locale-override]')){actions.hidden=!scriptSettings().overrides[actions.dataset.localeOverride];for(const button of actions.querySelectorAll('button'))button.disabled=busy;}}
 subscribeScripts(paint);paint();
 page.querySelector('[data-locale-scan]').onclick=async(event)=>{const button=event.currentTarget;button.disabled=true;try{const report=await scanEnglish(()=>{status.textContent='화면의 영어를 찾고 있어요…';});const output=page.querySelector('[data-locale-result]');output.hidden=false;output.value=typeof report==='string'?report:report.text;status.textContent='결과를 복사해서 보내 주세요.';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
}
