// Blue Lemonade layout, adapted from the LLM Translator connection/settings flow.
export function settingsHTML({c,esc,languages,providers,models,profiles}) {
 const field=(id,label,input,help='')=>`<div class="pt-field"><label for="${id}">${label}</label>${input}${help?`<p class="pt-bl-help">${help}</p>`:''}</div>`;
 const number=(id,label,value,min,max,help='')=>field(id,label,`<input id="${id}" type="number" min="${min}" max="${max}" value="${value}">`,help);
 const select=(id,label,options,help='')=>field(id,label,`<select id="${id}">${options}</select>`,help);
 const card=(title,body)=>`<section class="pt-card"><h4>${title}</h4>${body}</section>`;
 const langs=[['title','제목',c.titleLang,c.titleCustomLang,'pt-custom-title-lang'],['target','본문',c.targetLang,c.customLang,'pt-custom-lang'],['note','주석',c.noteLang,c.noteCustomLang,'pt-custom-note-lang']].map(([key,label,value,custom,id])=>select(`pt-${key}-lang`,label,languages(value))+`<div id="${id}-row" style="${value==='__custom__'?'':'display:none'}">${field(id,'직접 입력',`<input id="${id}" value="${esc(custom||'')}" placeholder="예: French">`)}</div>`).join('');
 return `<div class="pt-extension-settings"><div class="inline-drawer"><div class="inline-drawer-toggle inline-drawer-header"><b><i class="fa-solid fa-language" aria-hidden="true"></i> 한글화 패널 <span class="pt-drawer-version ext-version" role="button" tabindex="0" data-pt-guide aria-label="한글화 패널 사용방법">v1.1.0</span></b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div></div><div class="inline-drawer-content"><div id="pt-drawer-host"></div></div></div></div>
 <div id="pt-settings-form">
 <nav class="pt-settings-nav" role="tablist" aria-label="패널 설정 메뉴">${[['connection','연결'],['translation','번역'],['display','화면'],['storage','저장']].map(([id,name],i)=>`<button type="button" role="tab" id="pt-setting-tab-${id}" aria-controls="pt-setting-${id}" aria-selected="${!i}" data-setting-tab="${id}">${name}</button>`).join('')}</nav>
 <div class="pt-settings-scroll">
 <section id="pt-setting-connection" role="tabpanel" aria-labelledby="pt-setting-tab-connection" data-setting-page="connection">
 ${card('연결 방식',select('pt-connection-mode','번역에 쓸 연결',`<option value="current">현재 연결된 API · 모델 따라가기</option><option value="direct">실리태번 API 중 선택</option><option value="profile">저장된 ST 프로필 사용</option>`)+`<p id="pt-current-hint" class="pt-bl-help">LLM 번역과 같은 방식으로 현재 연결을 따라가요. 본체에서 모델을 바꾸면 다음 요청부터 반영됩니다.</p><div id="pt-current-options">${number('pt-active-max','최대 응답 토큰',c.activeMaxTokens||0,0,160000,'0이면 현재 연결의 응답 길이 설정을 따라가요.')}</div><button type="button" id="pt-import-llm" class="pt-ui-button">LLM 번역 설정 가져오기</button><p id="pt-connection-status" role="status"></p>`)}
 <div id="pt-profile-settings">${card('저장된 프로필',select('pt-profile-select','프로필',profiles,'프로필의 API·모델·키·프리셋을 사용해요. 본체에서 선택한 프로필은 바꾸지 않아요.'))}</div>
 <div id="pt-direct-settings">
 ${card('공급자 · 모델',select('pt-provider','공급자',providers)+`<div id="pt-custom-endpoint">${field('pt-custom-url','커스텀 엔드포인트 주소',`<input id="pt-custom-url" type="url" value="${esc(c.customUrl||'')}" placeholder="https://example.com/v1">`,'비워두면 본체의 Custom 주소·추가 헤더·Body를 사용해요. API 키는 본체 Custom 연결에 저장된 키를 사용합니다.')}<button type="button" id="pt-fetch-models" class="pt-ui-button">모델 목록 불러오기</button><p id="pt-models-status" role="status"></p></div>`+select('pt-model-select','모델',models,'API 키는 실리태번 본체에 저장된 키를 사용해요. 목록에 없으면 직접 입력하세요.')+`<div id="pt-custom-model-row" style="${c.model==='__custom__'?'':'display:none'}">${field('pt-model-custom','모델명 입력',`<input id="pt-model-custom" value="${esc(c.customModelName||'')}" placeholder="정확한 모델 ID">`)}</div>`)}
 ${card('생성 파라미터','<div id="pt-params-wrap"></div>')}
 ${card('중계 서버',`<label id="pt-proxy-toggle-row" class="pt-check"><input type="checkbox" id="pt-use-proxy" ${c.useReverseProxy?'checked':''}><span>리버스 프록시 사용</span></label><div id="pt-proxy-wrap" style="${c.useReverseProxy?'':'display:none'}">${field('pt-proxy-url','프록시 URL',`<input id="pt-proxy-url" type="url" value="${esc(c.reverseProxyUrl||'')}" placeholder="https://...">`)}${field('pt-proxy-pw','프록시 비밀번호',`<input id="pt-proxy-pw" type="password" value="${esc(c.reverseProxyPassword||'')}" autocomplete="off">`)}</div>`)}
 </div></section>
 <section id="pt-setting-translation" role="tabpanel" aria-labelledby="pt-setting-tab-translation" data-setting-page="translation" hidden>
 ${card('번역 언어',langs)}
 ${card('요청 속도와 재시도',number('pt-title-batch','제목 번역 묶음 개수',c.titleBatchSize,1,50,'한 번에 번역할 제목 수예요. 본문은 항목별로 요청해요.')+number('pt-concurrency','동시 번역 요청 수',c.concurrency,1,8,'처음에는 1로 시작하세요. 요청 한도 오류가 나면 낮춰요.')+number('pt-req-delay','요청 간 대기(ms)',c.requestDelayMs,0,60000,'1000ms는 1초예요.')+number('pt-max-retries','실패 시 재시도 횟수',c.maxRetries,0,5)+number('pt-req-timeout','요청 제한 시간(초)',Math.round(c.requestTimeoutMs/1000),5,600))}
 ${card('프리필',`<label class="pt-check"><input id="pt-prefill-toggle" type="checkbox" ${c.prefillEnabled?'checked':''}><span>번역 프리필 사용</span></label><textarea id="pt-prefill-text" aria-label="번역 프리필 내용" rows="3">${esc(c.prefillText||'')}</textarea><p class="pt-bl-help">답변 시작 문장을 미리 지정해요. 지원하지 않는 모델에서는 꺼 주세요.</p>`)}
 </section>
 <section id="pt-setting-display" role="tabpanel" aria-labelledby="pt-setting-tab-display" data-setting-page="display" hidden>
 ${card('글자와 설명',`<p class="pt-bl-help">색상은 블루레몬에이드를 따라가요. 패널 안의 원문과 번역문 크기를 따로 정할 수 있어요.</p><div class="pt-field"><label for="pt-orig-size">원문 글자 크기 <span id="pt-orig-size-val">${c.originalFontSize}px</span></label><input id="pt-orig-size" type="range" min="9" max="22" value="${c.originalFontSize}"></div><div class="pt-field"><label for="pt-trans-size">번역문 글자 크기 <span id="pt-trans-size-val">${c.translatedFontSize}px</span></label><input id="pt-trans-size" type="range" min="10" max="24" value="${c.translatedFontSize}"></div><label class="pt-check"><input id="pt-help-check" type="checkbox" ${c.blShowHelp!==false?'checked':''}><span>설정과 작업 화면에 설명 표시</span></label><button type="button" class="pt-ui-button" data-pt-guide>사용방법 열기</button>`)}
 </section>
 <section id="pt-setting-storage" role="tabpanel" aria-labelledby="pt-setting-tab-storage" data-setting-page="storage" hidden>
 ${card('번역 캐시',`<p>저장된 번역 <strong id="pt-cache-stats">–</strong></p><p class="pt-bl-help">번역 결과를 다시 사용하기 위한 저장소예요. 삭제해도 원본에 적용한 내용을 되돌리지는 않아요. 필요한 번역은 먼저 내보내세요.</p><button type="button" id="pt-clear-cache-btn" class="pt-ui-button">전체 캐시 삭제</button>`)}
 </section></div></div>`;
}
